### ISSUE TITLE
NuGet

### ISSUE THREAD

**Issue by HakanL** [ekonbenefits/NachaSharp#2]
It would be great if you could push this to NuGet as well.

**Comment by jbtule** [comment]
It will be, we are about to use this in production and then we will publish it to actual nuget.
It does have a myget feed, right now.
https://www.myget.org/feed/ci-fsharp-flatfilemeta/package/nuget/NachaSharp

**Comment by HakanL** [comment]
Yea I found the myget feed, but it's more work to use that in a solution than the standard nuget feeds. Maybe push it to NuGet as pre-release? What's the time frame for the production release?

**Comment by jbtule** [comment]
I just added the prereleases to nuget, it's still waiting to be indexed but they will show up there.

**Comment by HakanL** [comment]
That’s awesome, thank you!
